# Machine-specific settings on top of the hardware-configuration.nix
# generated by ‘nixos-generate-config’.

{ config, lib, pkgs, ... }:

{
  imports =
    [
      ./templates/raspberry-pi-4.nix

      ./locations/torres-del-paine.nix

      ./templates/cgroups2.nix
    ];

  networking = {
    hostName = "raspberry-pi";
    interfaces = {
      eth0.useDHCP = true;
      wlan0.useDHCP = true;
    };

    # wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  };
}

